services:
  gateway:
    image: nginx:latest
    ports:
      - '8000:80'
    depends_on:
      hotel-service:
        condition: service_started
      booking-service:
        condition: service_started
    volumes:
      - ./nginx/nginx.conf:/etc/nginx/conf.d/default.conf:ro

  booking-service:
    build: ./booking-service
    depends_on:
      mongo:
        condition: service_healthy
      redis:
        condition: service_healthy
    environment:
      SPRING_DATA_MONGODB_URI: ${MONGO_URI}
      HOTEL_SERVICE_URI: ${HOTEL_SERVICE_URI}
      REDIS_HOST: ${REDIS_HOST}
      REDIS_PORT: ${REDIS_PORT}

  hotel-service:
    build: ./hotel-service
    depends_on:
      postgres:
        condition: service_healthy
      redis:
        condition: service_healthy
    environment:
      PGUSER: ${PGUSER}
      PGPASSWORD: ${PGPASSWORD}
      PGDATABASE: ${PGDATABASE}
      PGHOST: postgres
      PGPORT: 5432

  mongo:
    image: mongo:7
    restart: unless-stopped
    healthcheck:
      test: ["CMD", "mongosh", "--eval", "db.adminCommand('ping')"]
      interval: 10s
      timeout: 5s
      retries: 5
    volumes:
      - mongo-data:/data/db

  postgres:
    image: postgres:16
    environment:
      POSTGRES_USER: ${PGUSER}
      POSTGRES_PASSWORD: ${PGPASSWORD}
      POSTGRES_DB: ${PGDATABASE}
    healthcheck:
      test:
        ['CMD-SHELL', 'pg_isready -U ${PGUSER} -d ${PGDATABASE} -h localhost']
      interval: 10s
      timeout: 5s
      retries: 5
    volumes:
      - postgres_data:/var/lib/postgresql/data

  redis:
    image: redis:latest
    restart: unless-stopped
    healthcheck:
      test: ["CMD", "redis-cli", "ping"]
      interval: 10s
      timeout: 5s
      retries: 5
    volumes:
      - redis_data:/data

volumes:
  mongo-data:
  postgres_data:
  redis_data: