spring.application.name=booking-service
spring.main.banner-mode=off
spring.mongodb.uri=${SPRING_DATA_MONGODB_URI}
service.hotel.uri=${HOTEL_SERVICE_URI}
spring.data.redis.host=${REDIS_HOST}
spring.data.redis.port=${REDIS_PORT}
server.port=3000
