upstream booking_backend {
    server booking-service:3000;
}

upstream hotel_backend {
    server hotel-service:3002;
}

server {
    listen 80;

    location /api/bookings/ {
        proxy_pass http://booking_backend/bookings/;
        proxy_set_header Host $host;
        proxy_set_header X-Real-IP $remote_addr;
    }

    location /api/ {
        proxy_pass http://hotel_backend/;
        proxy_set_header Host $host;
        proxy_set_header X-Real-IP $remote_addr;
    }
}